import "../globals.css"

export const metadata = {
  title: 'Symphonize, Inc - Please SignIn',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <div className="content flex flex-row flex-wrap">
          <aside className="w-0 sm:w-2/3  flex items-center justify-center bg-no-repeat bg-center bg-[url('https://assets-global.website-files.com/634690d9583ce36a5e30c703/65dd6b2e771607d2adcf1925_Group%201186.svg')]">
            <h1 className="text-6xl mb-5 font-bold leading-tight tracking-tight text-white md:text-6xl">Amplify your digital transformation</h1>
          </aside>
          <main className="flex-grow pt-1 p-2 bg-white">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
